package com.jesson.belle.dao.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table COLLECTED_BELLE.
 */
public class CollectedBelle {

    /** Not-null value. */
    private String url;
    private long time;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public CollectedBelle() {
    }

    public CollectedBelle(String url) {
        this.url = url;
    }

    public CollectedBelle(String url, long time) {
        this.url = url;
        this.time = time;
    }

    /** Not-null value. */
    public String getUrl() {
        return url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrl(String url) {
        this.url = url;
    }

    public long getTime() {
        return time;
    }

    public void setTime(long time) {
        this.time = time;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
