package com.jesson.sexybelle.dao.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig localBelleDaoConfig;
    private final DaoConfig collectedBelleDaoConfig;
    private final DaoConfig seriesDaoConfig;

    private final LocalBelleDao localBelleDao;
    private final CollectedBelleDao collectedBelleDao;
    private final SeriesDao seriesDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        localBelleDaoConfig = daoConfigMap.get(LocalBelleDao.class).clone();
        localBelleDaoConfig.initIdentityScope(type);

        collectedBelleDaoConfig = daoConfigMap.get(CollectedBelleDao.class).clone();
        collectedBelleDaoConfig.initIdentityScope(type);

        seriesDaoConfig = daoConfigMap.get(SeriesDao.class).clone();
        seriesDaoConfig.initIdentityScope(type);

        localBelleDao = new LocalBelleDao(localBelleDaoConfig, this);
        collectedBelleDao = new CollectedBelleDao(collectedBelleDaoConfig, this);
        seriesDao = new SeriesDao(seriesDaoConfig, this);

        registerDao(LocalBelle.class, localBelleDao);
        registerDao(CollectedBelle.class, collectedBelleDao);
        registerDao(Series.class, seriesDao);
    }
    
    public void clear() {
        localBelleDaoConfig.getIdentityScope().clear();
        collectedBelleDaoConfig.getIdentityScope().clear();
        seriesDaoConfig.getIdentityScope().clear();
    }

    public LocalBelleDao getLocalBelleDao() {
        return localBelleDao;
    }

    public CollectedBelleDao getCollectedBelleDao() {
        return collectedBelleDao;
    }

    public SeriesDao getSeriesDao() {
        return seriesDao;
    }

}
