package com.jesson.sexybelle.dao.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table LOCAL_BELLE.
 */
public class LocalBelle {

    private long id;
    private long time;
    private int type;
    /** Not-null value. */
    private String url;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public LocalBelle() {
    }

    public LocalBelle(long id, long time, int type, String url) {
        this.id = id;
        this.time = time;
        this.type = type;
        this.url = url;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public long getTime() {
        return time;
    }

    public void setTime(long time) {
        this.time = time;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    /** Not-null value. */
    public String getUrl() {
        return url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrl(String url) {
        this.url = url;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
